spring:
  application:
    name: my_fschool_backend
  datasource:
    url: jdbc:postgresql://localhost:5432/my_fschool
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

speedsms:
  access-token: ${SPEEDSMS_ACCESS_TOKEN}
  device-id: ${SPEEDSMS_DEVICE_ID} # Nếu xài tài khoản thử nghiệm chưa duyệt Brandname thì cứ để trống ""
